[package]
name = "blokator"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"
strip = "none"

[profile.release]
panic = "abort"

[dependencies]
clap = { version = "3.2.17", default-features = false, features = ["std", "derive"] }
dirs = { version = "4.0.0", default-features = false }
nix = { version = "0.25.0" }
reqwest = { version = "0.11.11", features = ["blocking"] }

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.8", features = ["winuser", "handleapi", "processthreadsapi", "securitybaseapi"]}
libc = "0.2.66"
