[package]
name = "blokator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"
strip = "none"

[profile.release]
panic = "abort"

[dependencies]
clap = { version = "3.2.17", default-features = false, features = ["std", "derive"] }
dirs = "4.0.0"
nix = "0.25.0"
ureq = "2.5.0"
