[preset]
adaway = "https://adaway.org/hosts.txt"
stevenblack = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
energized-spark = "https://block.energized.pro/spark/formats/hosts"
energized-blu-go = "https://block.energized.pro/bluGo/formats/hosts"
energized-blu = "https://block.energized.pro/blu/formats/hosts"
energized-basic = "https://block.energized.pro/basic/formats/hosts"
energized-porn = "https://block.energized.pro/porn/formats/hosts"
energized-ultimate = "https://block.energized.pro/ultimate/formats/hosts"
energized-unified = "https://block.energized.pro/unified/formats/hosts"
